import 'package:uuid/uuid.dart';

enum ShortcutAction {
  newConnection,
  profiles,
  discovery,
  keys,
  tabChar,
  arrowUp,
  arrowDown,
  arrowLeft,
  arrowRight,
  home,
  end,
  escapeKey,
  ctrlA,
  ctrlB,
  ctrlC,
  ctrlD,
  ctrlE,
  ctrlF,
  ctrlG,
  ctrlH,
  ctrlJ,
  ctrlK,
  ctrlL,
  ctrlN,
  ctrlO,
  ctrlP,
  ctrlQ,
  ctrlR,
  ctrlS,
  ctrlT,
  ctrlU,
  ctrlW,
  ctrlX,
  ctrlY,
  ctrlZ,
  ctrlV,
}

class KeyboardShortcut {
  final String id;
  final String label;
  final String description;
  final ShortcutAction action;
  final int? charCode;
  final int row;

  KeyboardShortcut({
    required this.label,
    required this.description,
    required this.action,
    String? id,
    this.charCode,
    this.row = 0,
  }) : id = id ?? const Uuid().v4();

  String get actionName {
    return switch (action) {
      ShortcutAction.newConnection => 'new_connection',
      ShortcutAction.profiles => 'profiles',
      ShortcutAction.discovery => 'discovery',
      ShortcutAction.keys => 'keys',
      ShortcutAction.tabChar => 'tab_char',
      ShortcutAction.arrowUp => 'arrow_up',
      ShortcutAction.arrowDown => 'arrow_down',
      ShortcutAction.arrowLeft => 'arrow_left',
      ShortcutAction.arrowRight => 'arrow_right',
      ShortcutAction.home => 'home',
      ShortcutAction.end => 'end',
      ShortcutAction.escapeKey => 'escape_key',
      ShortcutAction.ctrlA => 'ctrl_a',
      ShortcutAction.ctrlB => 'ctrl_b',
      ShortcutAction.ctrlC => 'ctrl_c',
      ShortcutAction.ctrlD => 'ctrl_d',
      ShortcutAction.ctrlE => 'ctrl_e',
      ShortcutAction.ctrlF => 'ctrl_f',
      ShortcutAction.ctrlG => 'ctrl_g',
      ShortcutAction.ctrlH => 'ctrl_h',
      ShortcutAction.ctrlJ => 'ctrl_j',
      ShortcutAction.ctrlK => 'ctrl_k',
      ShortcutAction.ctrlL => 'ctrl_l',
      ShortcutAction.ctrlN => 'ctrl_n',
      ShortcutAction.ctrlO => 'ctrl_o',
      ShortcutAction.ctrlP => 'ctrl_p',
      ShortcutAction.ctrlQ => 'ctrl_q',
      ShortcutAction.ctrlR => 'ctrl_r',
      ShortcutAction.ctrlS => 'ctrl_s',
      ShortcutAction.ctrlT => 'ctrl_t',
      ShortcutAction.ctrlU => 'ctrl_u',
      ShortcutAction.ctrlW => 'ctrl_w',
      ShortcutAction.ctrlX => 'ctrl_x',
      ShortcutAction.ctrlY => 'ctrl_y',
      ShortcutAction.ctrlZ => 'ctrl_z',
      ShortcutAction.ctrlV => 'ctrl_v',
    };
  }

  static String displayNameFor(ShortcutAction action) {
    return switch (action) {
      ShortcutAction.newConnection => 'New Connection',
      ShortcutAction.profiles => 'Profiles',
      ShortcutAction.discovery => 'Discovery',
      ShortcutAction.keys => 'Keys',
      ShortcutAction.tabChar => 'Tab',
      ShortcutAction.arrowUp => 'Arrow Up',
      ShortcutAction.arrowDown => 'Arrow Down',
      ShortcutAction.arrowLeft => 'Arrow Left',
      ShortcutAction.arrowRight => 'Arrow Right',
      ShortcutAction.home => 'Home',
      ShortcutAction.end => 'End',
      ShortcutAction.escapeKey => 'Esc',
      ShortcutAction.ctrlA => 'Ctrl+A',
      ShortcutAction.ctrlB => 'Ctrl+B',
      ShortcutAction.ctrlC => 'Ctrl+C (Interrupt)',
      ShortcutAction.ctrlD => 'Ctrl+D (EOF)',
      ShortcutAction.ctrlE => 'Ctrl+E',
      ShortcutAction.ctrlF => 'Ctrl+F',
      ShortcutAction.ctrlG => 'Ctrl+G (Help)',
      ShortcutAction.ctrlH => 'Ctrl+H',
      ShortcutAction.ctrlJ => 'Ctrl+J',
      ShortcutAction.ctrlK => 'Ctrl+K (Cut)',
      ShortcutAction.ctrlL => 'Ctrl+L (Clear)',
      ShortcutAction.ctrlN => 'Ctrl+N',
      ShortcutAction.ctrlO => 'Ctrl+O (Write)',
      ShortcutAction.ctrlP => 'Ctrl+P',
      ShortcutAction.ctrlQ => 'Ctrl+Q',
      ShortcutAction.ctrlR => 'Ctrl+R',
      ShortcutAction.ctrlS => 'Ctrl+S',
      ShortcutAction.ctrlT => 'Ctrl+T',
      ShortcutAction.ctrlU => 'Ctrl+U (Uncut)',
      ShortcutAction.ctrlW => 'Ctrl+W (Search)',
      ShortcutAction.ctrlX => 'Ctrl+X (Exit)',
      ShortcutAction.ctrlY => 'Ctrl+Y',
      ShortcutAction.ctrlZ => 'Ctrl+Z (Suspend)',
      ShortcutAction.ctrlV => 'Paste',
    };
  }

  static String defaultLabelFor(ShortcutAction action) {
    return switch (action) {
      ShortcutAction.newConnection => 'Ctrl+N',
      ShortcutAction.profiles => 'Ctrl+P',
      ShortcutAction.discovery => 'Ctrl+D',
      ShortcutAction.keys => 'Ctrl+K',
      ShortcutAction.tabChar => 'Tab',
      ShortcutAction.arrowUp => '↑',
      ShortcutAction.arrowDown => '↓',
      ShortcutAction.arrowLeft => '←',
      ShortcutAction.arrowRight => '→',
      ShortcutAction.home => 'Home',
      ShortcutAction.end => 'End',
      ShortcutAction.escapeKey => 'Esc',
      ShortcutAction.ctrlA => 'Ctrl+A',
      ShortcutAction.ctrlB => 'Ctrl+B',
      ShortcutAction.ctrlC => 'Ctrl+C',
      ShortcutAction.ctrlD => 'Ctrl+D',
      ShortcutAction.ctrlE => 'Ctrl+E',
      ShortcutAction.ctrlF => 'Ctrl+F',
      ShortcutAction.ctrlG => 'Ctrl+G',
      ShortcutAction.ctrlH => 'Ctrl+H',
      ShortcutAction.ctrlJ => 'Ctrl+J',
      ShortcutAction.ctrlK => 'Ctrl+K',
      ShortcutAction.ctrlL => 'Ctrl+L',
      ShortcutAction.ctrlN => 'Ctrl+N',
      ShortcutAction.ctrlO => 'Ctrl+O',
      ShortcutAction.ctrlP => 'Ctrl+P',
      ShortcutAction.ctrlQ => 'Ctrl+Q',
      ShortcutAction.ctrlR => 'Ctrl+R',
      ShortcutAction.ctrlS => 'Ctrl+S',
      ShortcutAction.ctrlT => 'Ctrl+T',
      ShortcutAction.ctrlU => 'Ctrl+U',
      ShortcutAction.ctrlW => 'Ctrl+W',
      ShortcutAction.ctrlX => 'Ctrl+X',
      ShortcutAction.ctrlY => 'Ctrl+Y',
      ShortcutAction.ctrlZ => 'Ctrl+Z',
      ShortcutAction.ctrlV => 'Ctrl+V',
    };
  }

  static String defaultDescriptionFor(ShortcutAction action) {
    return switch (action) {
      ShortcutAction.newConnection => 'New Connection',
      ShortcutAction.profiles => 'Profiles',
      ShortcutAction.discovery => 'Discovery',
      ShortcutAction.keys => 'Keys',
      ShortcutAction.tabChar => 'Tab',
      ShortcutAction.arrowUp => 'Arrow Up',
      ShortcutAction.arrowDown => 'Arrow Down',
      ShortcutAction.arrowLeft => 'Arrow Left',
      ShortcutAction.arrowRight => 'Arrow Right',
      ShortcutAction.home => 'Home',
      ShortcutAction.end => 'End',
      ShortcutAction.escapeKey => 'Escape',
      ShortcutAction.ctrlA => 'Select All / Line Start',
      ShortcutAction.ctrlB => 'Backward Char',
      ShortcutAction.ctrlC => 'Interrupt',
      ShortcutAction.ctrlD => 'EOF',
      ShortcutAction.ctrlE => 'Line End',
      ShortcutAction.ctrlF => 'Forward Char',
      ShortcutAction.ctrlG => 'Help',
      ShortcutAction.ctrlH => 'Backspace',
      ShortcutAction.ctrlJ => 'Line Feed',
      ShortcutAction.ctrlK => 'Cut',
      ShortcutAction.ctrlL => 'Clear',
      ShortcutAction.ctrlN => 'Next',
      ShortcutAction.ctrlO => 'Write Out',
      ShortcutAction.ctrlP => 'Previous',
      ShortcutAction.ctrlQ => 'Quit / XON',
      ShortcutAction.ctrlR => 'Reverse Search',
      ShortcutAction.ctrlS => 'Save / XOFF',
      ShortcutAction.ctrlT => 'Transpose',
      ShortcutAction.ctrlU => 'Uncut / Kill Line',
      ShortcutAction.ctrlW => 'Search / Kill Word',
      ShortcutAction.ctrlX => 'Exit',
      ShortcutAction.ctrlY => 'Yank',
      ShortcutAction.ctrlZ => 'Suspend',
      ShortcutAction.ctrlV => 'Paste',
    };
  }

  static int? defaultCharCodeFor(ShortcutAction action) {
    return switch (action) {
      ShortcutAction.tabChar => 9,
      ShortcutAction.escapeKey => 27,
      ShortcutAction.ctrlA => 1,
      ShortcutAction.ctrlB => 2,
      ShortcutAction.ctrlC => 3,
      ShortcutAction.ctrlD => 4,
      ShortcutAction.ctrlE => 5,
      ShortcutAction.ctrlF => 6,
      ShortcutAction.ctrlG => 7,
      ShortcutAction.ctrlH => 8,
      ShortcutAction.ctrlJ => 10,
      ShortcutAction.ctrlK => 11,
      ShortcutAction.ctrlL => 12,
      ShortcutAction.ctrlN => 14,
      ShortcutAction.ctrlO => 15,
      ShortcutAction.ctrlP => 16,
      ShortcutAction.ctrlQ => 17,
      ShortcutAction.ctrlR => 18,
      ShortcutAction.ctrlS => 19,
      ShortcutAction.ctrlT => 20,
      ShortcutAction.ctrlU => 21,
      ShortcutAction.ctrlW => 23,
      ShortcutAction.ctrlX => 24,
      ShortcutAction.ctrlY => 25,
      ShortcutAction.ctrlZ => 26,
      _ => null,
    };
  }

  static List<ShortcutAction> actionsForRow(int row) {
    return switch (row) {
      0 => <ShortcutAction>[
          ShortcutAction.newConnection,
          ShortcutAction.profiles,
          ShortcutAction.discovery,
          ShortcutAction.keys,
        ],
      1 => <ShortcutAction>[
          ShortcutAction.tabChar,
          ShortcutAction.arrowLeft,
          ShortcutAction.arrowRight,
          ShortcutAction.arrowUp,
          ShortcutAction.arrowDown,
          ShortcutAction.home,
          ShortcutAction.end,
          ShortcutAction.ctrlV,
        ],
      _ => <ShortcutAction>[
          ShortcutAction.escapeKey,
          ShortcutAction.ctrlC,
          ShortcutAction.ctrlD,
          ShortcutAction.ctrlZ,
          ShortcutAction.ctrlL,
          ShortcutAction.ctrlA,
          ShortcutAction.ctrlP,
          ShortcutAction.ctrlG,
          ShortcutAction.ctrlK,
          ShortcutAction.ctrlO,
          ShortcutAction.ctrlR,
          ShortcutAction.ctrlS,
          ShortcutAction.ctrlT,
          ShortcutAction.ctrlU,
          ShortcutAction.ctrlW,
          ShortcutAction.ctrlX,
          ShortcutAction.ctrlQ,
          ShortcutAction.ctrlV,
        ],
    };
  }

  static KeyboardShortcut createForAction(
    ShortcutAction action, {
    required int row,
    String? id,
    String? label,
    String? description,
  }) {
    return KeyboardShortcut(
      id: id,
      label: label ?? defaultLabelFor(action),
      description: description ?? defaultDescriptionFor(action),
      action: action,
      charCode: defaultCharCodeFor(action),
      row: row,
    );
  }

  KeyboardShortcut copyWith({
    String? id,
    String? label,
    String? description,
    ShortcutAction? action,
    int? charCode,
    int? row,
  }) {
    return KeyboardShortcut(
      id: id ?? this.id,
      label: label ?? this.label,
      description: description ?? this.description,
      action: action ?? this.action,
      charCode: charCode ?? this.charCode,
      row: row ?? this.row,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'id': id,
      'label': label,
      'description': description,
      'action': actionName,
      'charCode': charCode,
      'row': row,
    };
  }

  factory KeyboardShortcut.fromJson(Map<String, dynamic> json) {
    return KeyboardShortcut(
      id: json['id'] as String,
      label: json['label'] as String,
      description: json['description'] as String,
      action: _actionFromString(json['action'] as String),
      charCode: json['charCode'] as int?,
      row: json['row'] as int? ?? 0,
    );
  }

  static ShortcutAction _actionFromString(String action) {
    return switch (action) {
      'new_connection' => ShortcutAction.newConnection,
      'profiles' => ShortcutAction.profiles,
      'discovery' => ShortcutAction.discovery,
      'keys' => ShortcutAction.keys,
      'tab_char' => ShortcutAction.tabChar,
      'arrow_up' => ShortcutAction.arrowUp,
      'arrow_down' => ShortcutAction.arrowDown,
      'arrow_left' => ShortcutAction.arrowLeft,
      'arrow_right' => ShortcutAction.arrowRight,
      'home' => ShortcutAction.home,
      'end' => ShortcutAction.end,
      'escape_key' => ShortcutAction.escapeKey,
      'ctrl_a' => ShortcutAction.ctrlA,
      'ctrl_b' => ShortcutAction.ctrlB,
      'ctrl_c' => ShortcutAction.ctrlC,
      'ctrl_d' => ShortcutAction.ctrlD,
      'ctrl_e' => ShortcutAction.ctrlE,
      'ctrl_f' => ShortcutAction.ctrlF,
      'ctrl_g' => ShortcutAction.ctrlG,
      'ctrl_h' => ShortcutAction.ctrlH,
      'ctrl_j' => ShortcutAction.ctrlJ,
      'ctrl_k' => ShortcutAction.ctrlK,
      'ctrl_l' => ShortcutAction.ctrlL,
      'ctrl_n' => ShortcutAction.ctrlN,
      'ctrl_o' => ShortcutAction.ctrlO,
      'ctrl_p' => ShortcutAction.ctrlP,
      'ctrl_q' => ShortcutAction.ctrlQ,
      'ctrl_r' => ShortcutAction.ctrlR,
      'ctrl_s' => ShortcutAction.ctrlS,
      'ctrl_t' => ShortcutAction.ctrlT,
      'ctrl_u' => ShortcutAction.ctrlU,
      'ctrl_w' => ShortcutAction.ctrlW,
      'ctrl_x' => ShortcutAction.ctrlX,
      'ctrl_y' => ShortcutAction.ctrlY,
      'ctrl_z' => ShortcutAction.ctrlZ,
      'ctrl_v' => ShortcutAction.ctrlV,
      _ => ShortcutAction.newConnection,
    };
  }

  static List<KeyboardShortcut> get defaults => <KeyboardShortcut>[
        createForAction(ShortcutAction.newConnection, row: 0),
        createForAction(ShortcutAction.profiles, row: 0),
        createForAction(ShortcutAction.discovery, row: 0),
        createForAction(ShortcutAction.keys, row: 0),
        createForAction(ShortcutAction.tabChar, row: 1),
        createForAction(ShortcutAction.arrowLeft, row: 1),
        createForAction(ShortcutAction.arrowRight, row: 1),
        createForAction(ShortcutAction.arrowUp, row: 1),
        createForAction(ShortcutAction.arrowDown, row: 1),
        createForAction(ShortcutAction.home, row: 1),
        createForAction(ShortcutAction.end, row: 1),
        createForAction(ShortcutAction.ctrlC, row: 2),
        createForAction(ShortcutAction.ctrlD, row: 2),
        createForAction(ShortcutAction.ctrlZ, row: 2),
        createForAction(ShortcutAction.ctrlL, row: 2),
        createForAction(ShortcutAction.ctrlX, row: 2),
        createForAction(ShortcutAction.ctrlO, row: 2),
        createForAction(ShortcutAction.ctrlW, row: 2),
        createForAction(ShortcutAction.ctrlK, row: 2),
        createForAction(ShortcutAction.ctrlU, row: 2),
        createForAction(ShortcutAction.ctrlG, row: 2),
        createForAction(ShortcutAction.escapeKey, row: 2),
        createForAction(ShortcutAction.ctrlV, row: 2),
      ];
}
